// ROSM base class

var ROSM = {};
ROSM.GLOBALS = {};
ROSM.CONSTANTS = {};
ROSM.DEFAULTS = {};
ROSM.C = ROSM.CONSTANTS;
ROSM.G = ROSM.GLOBALS;

ROSM.CONSTANTS.SOURCE_LABEL = "Van";
ROSM.CONSTANTS.TARGET_LABEL = "Naar";
ROSM.CONSTANTS.VIA_LABEL = "via";

ROSM.DEFAULTS.ZOOM_LEVEL = 14;
ROSM.DEFAULTS.HOST_GEOCODER_URL = "http://nominatim.openstreetmap.org/search";
